### ISSUE TITLE
cargo.toml -> Cargo.toml

### ISSUE THREAD

**Issue by nitrram** [F0rty-Tw0/hann-rs#1]
When pulling the crate out of crates.io it fails to compile via `cargo build` as it cannot find `Cargo.toml`. It perhaps has something to do with the OS's case-sensitivity. Renaming `cargo.toml` to `Cargo.toml` should do the trick fixing the issue and make it more general in terms of what OS cargo is being run on

**Comment by F0rty-Tw0** [comment]
Hi Martin, 

Thanks for this issue, you can contribute and open a pull request with the fix.

Best,
Art
